version: 2
updates:
  # npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
    versioning-strategy: "increase"
    groups:
      vue:
        patterns:
          - "vue"
          - "vue-router"
          - "vue-tsc"
          - "@vue/*"
          - "@vitejs/plugin-vue"
          - "vite-plugin-vue-*"
          - "eslint-plugin-vue"
      vite:
        patterns:
          - "vite"
          - "vitest"
          - "@vitest/*"
      tailwindcss:
        patterns:
          - "tailwindcss"
          - "@tailwindcss/*"
          - "prettier-plugin-tailwindcss"
      eslint:
        patterns:
          - "eslint"
          - "eslint-plugin-*"
          - "@eslint/*"
      types:
        patterns:
          - "@types/*"
          - "@tsconfig/*"
      openapi:
        patterns:
          - "openapi-fetch"
          - "openapi-typescript"
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"
