version: 2
updates:
  # npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
    versioning-strategy: "increase"
    reviewers:
      - "kageyamountain"
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "21:00"
      timezone: "Asia/Tokyo"
    open-pull-requests-limit: 20
    cooldown:
      default-days: 7
    reviewers:
      - "kageyamountain"
    assignees:
      - "kageyamountain"
    labels:
      - "dependencies"
