name: lint

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: Node.jsのセットアップ
        uses: actions/setup-node@2028fbc5c25fe9cf00d9f06a71cc4710d4507903 # v6.0.0
        with:
          node-version: '22.20.0'
          cache: 'npm'

      - name: 依存関係のインストール
        run: npm ci

      - name: 型チェック実行
        run: npm run type-check
        continue-on-error: false

      - name: lint実行
        run: npm run lint:check
        continue-on-error: false
