name: lint

on:
  pull_request:
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Node.jsのセットアップ
        uses: actions/setup-node@6044e13b5dc448c55e2357c09f80417699197238 # v6.2.0
        with:
          node-version: '22.20.0'
          cache: 'npm'

      - name: 依存関係のインストール
        run: npm ci

      - name: 型チェック実行
        run: npm run type-check
        continue-on-error: false

      - name: lint実行
        run: npm run lint:check
        continue-on-error: false
